installed_at: '2026-02-26T13:21:40+00:00'
skill_id: git/mastering-typescript
git_repo: https://github.com/SpillwaveSolutions/mastering-typescript-skill
skill_path: /tmp/skilz-git-zi6q7gbs/mastering-typescript
git_sha: 2f74a00f731f2ea4d48f45d852067a7be8efd0d1
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
